### ISSUE TITLE
[Easy] Duplicate log from function composition

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#120]
the log statement `"Fetching token data from EVM"` occurs in both `fetchTokenInfoFromExchange` and `fetchTokenInfoAtAddresses` while the former calls the later. This means (when debug == true) that we will observe identical log statements twice in a row.

Furthermore, although I am not entirely sure, but it appears this line

```js
const log = debug ? () => console.log.apply(arguments) : () => {}
```

could be moved out of individual functions as a global statement for the definition of `log`

**Comment by fedgiac** [comment]
Currently logging has many problems, for example the line you mention doesn't appear to be working, see issue #74.This issue has been neglected in the hope of eventually reworking how logging works in the code. This is especially needed since we started to rely on asynchronous calls in the code: the order in which the logging information is basically random, so you would see e.g. the orders of Safe 12 before that of Safe 1.
