### ISSUE TITLE
fetchTokenInfoFromExchange for non-standard tokens

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#226]
Anxo pointed out that fetchTokenInfoFromExchange should be adapted soo that it also works, if the tokens don't implement the ERC20 protocol, as for example, they don't define the symbol interface.

fetchTokenInfoFromExchange should consider this...

**Comment by fedgiac** [comment]
A related problem is that some tokens have a different return types for `.symbol()` and `.decimals()` than what is specified by ERC20Detailed, and this makes the call to them fail internally.

An example is the MKR token, where `symbol` is `byte32` instead of a string and `decimals` is `uint256` instead of `uint8`. Example execution causing this issue:
 ```
$ npx truffle exec scripts/complete_liquidity_provision.js --baseTokenId=23 --quoteTokenId=1 --lowestLimit=320 --highestLimit=720 --currentPrice=503 --masterSafe=0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740 --depositBaseToken=156.25 --depositQuoteToken=65000 --numBrackets=14 --network=mainnet
> Warning: possible unsupported (undocumented in help) command line option: --baseTokenId,--quoteTokenId,--lowestLimit,--highestLimit,--currentPrice,--masterSafe,--depositBaseToken,--depositQuoteToken,--numBrackets
Using network 'mainnet'.

Error: overflow (operation="setValue", fault="overflow", details="Number can only safely store up to 53 bits")
    at /path/dex-liquidity-provision/scripts/utils/trading_strategy_helpers.js:97:119
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /path/dex-liquidity-provision/scripts/utils/trading_strategy_helpers.js:133:29
Truffle v5.1.31 (core: 5.1.31)
Node v12.16.3
```

The line mentioned in the error message is:
```
const [tokenSymbol, tokenDecimals] = await Promise.all([tokenInstance.symbol(), tokenInstance.decimals()])
```

My first idea is to retrieve token information from a list first, and if it fails then swithc back to querying the contract. If also this fails, use some default string "UNKNOWN" for the name and fail if the number of decimals is not specified.

**Comment by fedgiac** [comment]
Note that the frontend at `dex-react` also needed to solve this issue. The solution [there](https://github.com/gnosis/dex-react/pull/967) ([whitelist](https://github.com/gnosis/dex-react/blob/9b6217e78dcc9d59a12f48d95197e04e2ee5c039/src/api/erc20/erc20Details.json)) is the same solution used in PR #324.
