### ISSUE TITLE
Scripts should gracefully fail when private key is not available

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#235]
Running for example `complete_liquidity_provision.js` when the private key has not be added as an env variable makes the script run for a while and then fail towards the end with:
```
TypeError: Cannot read property 'startsWith' of undefined
    at withHexPrefix (/path/dex-liquidity-provision/scripts/utils/sign_and_send.js:18:45)
    at signAndSend (/path/dex-liquidity-provision/scripts/utils/sign_and_send.js:66:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
All scripts that need a private key should tell the users that no private key is available.

**Comment by bh2smith** [comment]
This is already fixed in the code:

https://github.com/gnosis/dex-liquidity-provision/blob/4cbffbe42c6ec42ff523b83089cbc2d4041b9282/scripts/utils/sign_and_send.js#L73-L74

Originally introduced in #196 and moved a few lines lower in #219

**Comment by fedgiac** [comment]
This is what I get when running on Rinkeby without exporting `PK`, note that the brackets are deployed anyway since there are Ethers stored in the default address:
```
$ npx truffle exec scripts/complete_liquidity_provision.js --targetToken=1 --stableToken=4 --lowestLimit=180 --highestLimit=200 --currentPrice=190 --masterSafe=0xd9395aeE9141a3Efeb6d16057c8f67fBE296734c --investmentTargetToken=0.1 --investmentStableToken=2 --fleetSize=2 --network=rinkeby
> Warning: possible unsupported (undocumented in help) command line option: --targetToken,--stableToken,--lowestLimit,--highestLimit,--currentPrice,--masterSafe,--investmentTargetToken,--investmentStableToken,--fleetSize
Using network 'rinkeby'.

==> Performing safety checks
==> Deploying 2 trading brackets
[HDWalletProvider] Using nonce:  25774
==> Building orders and deposits
Batch Exchange 0xC576eA7bd102F7E476368a5E98FA455d1Ea34dE2
Constructing bracket trading strategy order data between the limits 180-200 USDC per WETH
Safe 0 - 0x1a01176E4eAFCcDDD87F227292A89716c6F73487:
  Buy  WETH with USDC at 180
  Sell WETH for  USDC at 189.73665961010278
Safe 1 - 0xeB345199388586AbB5999c8f08845463eB782715:
  Buy  WETH with USDC at 189.73665961010278
  Sell WETH for  USDC at 200.00000000000003
Transaction bundle size 4
==> Sending the order placing transaction to gnosis-safe interface.
    Attention: This transaction MUST be executed first!
Aquiring Transaction Hash
AssertionError [ERR_ASSERTION]: This script requires a private key be explicitly provided. Please export PK
    at signAndSend (/path/dex-liquidity-provision/scripts/utils/sign_and_send.js:63:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is what I get on mainnet with a similar command:
```
> Warning: possible unsupported (undocumented in help) command line option: --targetToken,--stableToken,--lowestLimit,--highestLimit,--currentPrice,--masterSafe,--investmentTargetToken,--investmentStableToken,--fleetSize
Using network 'mainnet'.

==> Performing safety checks
==> Deploying 20 trading brackets
[HDWalletProvider] Using nonce:  15865
Error: insufficient funds for gas * price + value
    at deployFleetOfSafes (/path/dex-liquidity-provision/scripts/utils/trading_strategy_helpers.js:210:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

So in the first case the script runs for a while and then fails, but with side effects. In the second case the script fails immediately but with an unhelpful error message. I'd argue this should be improved.

**Comment by bh2smith** [comment]
The problem you have in the second scenario is that you have insufficient funds to deploy the safes.

```
Error: insufficient funds for gas * price + value
```

This is because web3 is using a default account while the `sign_and_send` script parses your exported private key. I would agree this is completely inconsistent and would prefer if we allowed people to explicitly not provide and fall back to default when they do not. The reason I prefer this is because this is common among all our truffle projects at gnosis. This is declared in the truffle config file here

https://github.com/gnosis/dex-liquidity-provision/blob/37cf28e6440e7af0245675458f1e661a1ea9f2ad/truffle-config.js#L10-L15

I would hope that we can adjust `sign_and_send` to be aligned with this configuration. Usually we use `web3.eth.getAccounts()` as opposed to the "construct publicKey from private key" signing we are currently doing here:

https://github.com/gnosis/dex-liquidity-provision/blob/37cf28e6440e7af0245675458f1e661a1ea9f2ad/scripts/utils/sign_and_send.js#L63-L65


My guess would be that we can replace these line with `const account = (await web3.eth.getAccounts())[0]`. @josojo, is there a special reason you introduced the use of this `    const account = web3.eth.accounts.privateKeyToAccount` here?


Good catch on the inconsistency.
