### ISSUE TITLE
Missing Infura key in documentation

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#326]
Since the default Infura key in this project has been made invalid, users must specify their own Infura key. This extra step should be mentioned in the documentation. Error:
```
Error: There was a timeout while attempting to connect to the network.
       Check to see that your provider is valid.
       If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this.
    at Timeout.setTimeout (/path/dex-liquidity-provision/node_modules/truffle/build/webpack:/packages/provider/index.js:56:1)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by bh2smith** [comment]
Good issue here, I might suggest putting `INFURA_KEY` into the `.sample_env` perhaps along with `masterSafe` that should really be changed to `fundAccount` if it has not been already (at least then it would also agree with aridrop script parameters).

Having the `.sample_env` actually saves the user a lot of time since they can simply put all the configuration parameters there and run `source .sample_env` to export all the values at once.

**Comment by fedgiac** [comment]
Agreed that `INFURA_KEY` should appear in `.sample_env`. There should also be a nicer error message in case the key is not provided.

I don't like renaming `masterSafe` to `fundAccount`. The most important property of the master safe is that it controls the brackets after deployment, not that it holds funds before deployment. `fundAccount` is definitely a better name in the airdrop script however.
